name: MNIST DNN Build Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-windows:
    runs-on: windows-latest
    if: ${{ !contains(github.event.head_commit.message, '** SKIP TEST BUILD **') }}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run build test - mnist_dnn
      run: |
        pip install virtualenv 1> /dev/null 2> /dev/null
        source env_setup.sh --python-version python
        source dev/mnist-dnn-venv/Scripts/activate
        cd packages/dnn/
        pytest tests
        cd ../../
        
