name: MNIST DNN Build Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-macos:
    runs-on: windows-latest
    if: ${{ !contains(github.event.head_commit.message, '** SKIP TEST BUILD **') }}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: testing
    - run: |
        echo $SHELL
        echo testing
        git status
        pwd
        ls -al
        find . -name "env_setup.sh"
