name: MNIST DNN Build Test
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
jobs:
  build-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    if: ${{ !contains(github.event.head_commit.message, '** SKIP TEST BUILD **') && !contains(github.event.head_commit.message, 'DOP-') }}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Run build test - mnist_dnn
      run: |
        echo -en "\e[36mINSTALLING REQUIRED PACKAGES --- \e[0m"
        pip install -r 'packages/api/requirements.txt' 1> /dev/null 2> /dev/null
        pip install -r 'packages/dnn/requirements.txt' 1> /dev/null 2> /dev/null
        echo -e "\e[32mDone\e[0m"
        echo -e "\e[36mRUNNING 'mnist_dnn' TESTS\e[0m"
        pytest packages/dnn/tests
